---
name: Backport

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [closed, labeled]

permissions:
  contents: write  # so it can comment
  pull-requests: write  # so it can create pull requests

jobs:
  # yamllint disable rule:line-length
  backport:
    name: Backport Pull Request
    if: github.repository_owner == 'Freifunk-Rhein-Neckar' && github.event.pull_request.merged == true && (github.event_name != 'labeled' || startsWith('backport', github.event.label.name))
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/create-github-app-token@v2
        if: vars.GH_APP_ID != ''
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Create backport PRs
        uses: korthout/backport-action@v3.2.0
        with:
          # Config README: https://github.com/korthout/backport-action#backport-action
          pull_description: |-
            Automatic backport to `${target_branch}`, triggered by a label in #${pull_number}.
          github_token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
  # yamllint enable rule:line-length
